<?php 
namespace Avalara;
/*
 * AvaTax Software Development Kit for PHP
 *
 * (c) 2004-2017 Avalara, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @category   AvaTax client libraries
 * @package    Avalara.AvaTaxClient
 * @author     Ted Spence <ted.spence@avalara.com>
 * @author     Bob Maidens <bob.maidens@avalara.com>
 * @copyright  2004-2017 Avalara, Inc.
 * @license    https://www.apache.org/licenses/LICENSE-2.0
 * @version    17.7.0-96
 * @link       https://github.com/avadev/AvaTax-REST-V2-PHP-SDK
 */

use GuzzleHttp\Client;

/*****************************************************************************
 *                              API Section                                  *
 *                                                                           *
 *    This file is not automatically generated by the AvaTax SDK process.    *
 *                        You may edit this file.                            *
 *                                                                           *
 *****************************************************************************/

/**
 * An AvaTaxClient object that handles connectivity to the AvaTax v2 API server.
 */
class AvaTaxClient 
{
    include 'Client.php';
    
    include 'Methods.php';
}

include 'Models.php';

include 'Constants.php';

include 'TransactionBuilder.php';
